dataset_name: PFL-DocVQA-BLUE
imdb_dir: /data/shared/PFL-DocVQA/imdb/blue
images_dir: /data/shared/PFL-DocVQA/images/blue
images_h5_path: /data/shared/PFL-DocVQA/images/blue_images.h5

# used for dp provider-document mapping:
provider_docs: /data/shared/PFL-DocVQA/imdb/blue/centralized_data_points.json
# provider_client: /data/shared/PFL-DocVQA/imdb/blue/provider2client.json
